[project]
name = "evan_tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.14.0",
    "typer>=0.20.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["evan_tools"]
